# Generated by Django 5.1.7 on 2025-05-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='integer',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=500),
        ),
        migrations.AlterField(
            model_name='number',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=500),
        ),
        migrations.AlterField(
            model_name='score',
            name='increment',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=500),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=500),
        ),
    ]
