# Generated by Django 5.1.7 on 2025-05-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_number_integer_alter_number_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='time_stamp',
            new_name='last_updated',
        ),
    ]
