# Generated by Django 5.1.7 on 2025-05-12 18:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_time_stamp_score_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=500),
        ),
        migrations.AlterField(
            model_name='score',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_value',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=500),
        ),
    ]
