# Generated by Django 5.1.7 on 2025-05-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_number_quantity_alter_score_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='purchased_buttons',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='score',
            name='time_increment',
            field=models.DecimalField(decimal_places=10, default=30, max_digits=100),
        ),
    ]
