# Generated by Django 5.1.7 on 2025-05-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_score_purchased_buttons_score_time_increment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='purchased_buttons',
            field=models.IntegerField(default=0),
        ),
    ]
