# Generated by Django 5.1.7 on 2025-05-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_score_purchased_buttons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='purchased_buttons',
            field=models.IntegerField(default=1),
        ),
    ]
