# Generated by Django 5.1.7 on 2025-05-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_score_purchased_buttons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='time_increment',
            field=models.DecimalField(decimal_places=0, default=30, max_digits=3),
        ),
    ]
