# Generated by Django 5.1.7 on 2025-05-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_score_time_increment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='time_increment',
            field=models.IntegerField(default=15),
        ),
    ]
