# Generated by Django 5.1.7 on 2025-05-13 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_score_time_increment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='user',
        ),
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='number',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='app.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='game',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='app.game'),
            preserve_default=False,
        ),
    ]
