# Generated by Django 5.1.7 on 2025-05-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_number_user_remove_score_user_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='time_elapsed',
            field=models.IntegerField(default=1),
        ),
    ]
